version: "3.9"
name: geoflow_fr
services:
  pgdb:
    build: ./db

    container_name: pgdb

    env_file:
      - ./pg.env

    ports:
      - 5418:5432
  geoflow_custom:
    #image: geoflow-dim
    build: ./
    volumes:
      - ./config:/config
      - ./example_data/10_268_594/bati_ign:/data/poly
      - ./example_data/10_268_594/las_in/:/data/laz/ahn3
      - ./tmp:/tmp
      - ./output:/data/output
      - ./resources/:/dim_pipeline/resources
      - ./run.py/:/dim_pipeline/run.py
    environment:
      PG_OUTPUT: ${PG_OUTPUT}
    tty: true

  pg_3d:
    build: ./pg3d
    tty: true
    container_name: pg_3d

    volumes:
      - ./data:/data

    ports:
      - 5500:5500
    depends_on:
      - pgdb
