BID = 'BATIMENT0000000025230135'
CITYJSON_SCALE_X = 0.001
CITYJSON_SCALE_Y = 0.001
CITYJSON_SCALE_Z = 0.001
CITYJSON_TRANSLATE_X = 380950.29999999999
CITYJSON_TRANSLATE_Y = 6263549.0
CITYJSON_TRANSLATE_Z = 0.0
GF_PROCESS_CRS = 'EPSG:2154'
GF_PROCESS_OFFSET_OVERRIDE = true
GF_PROCESS_OFFSET_X = 380068.20000000001
GF_PROCESS_OFFSET_Y = 6263884.7000000002
GF_PROCESS_OFFSET_Z = 80.700000000000003
GROUND_ELEVATION = 82.840000104904178
INPUT_FOOTPRINT = '/tmp/features/BATIMENT0000000025230135/crop/BATIMENT0000000025230135.gpkg'
INPUT_POINTCLOUD = '/tmp/features/BATIMENT0000000025230135/crop/BATIMENT0000000025230135_AHN3.las'
OUTPUT_CRS = 'EPSG:2154'
OUTPUT_JSONL = '/data/output/features/BATIMENT0000000025230135.city.jsonl'
clip_ground = true
line_detect__epsilon = 0.59999999999999998
lod13__step_height = 3.0
optimisation_data_term = 10.0
plane_detect__epsilon = 0.20000000000000001
plane_detect__k = 50
plane_detect__min_points = 10
plane_detect__normal_angle = 0.75
plane_detect__ransac_cluster_epsilon = 0.29999999999999999
plane_detect__ransac_probability = 0.050000000000000003
plane_detect__use_ransac = false
plane_reg__angle = 10.0
plane_reg__axis_symmetry = false
plane_reg__coplanarity = true
plane_reg__offset = 0.40000000000000002
plane_reg__orthogonality = false
plane_reg__parallelism = false
skip_attribute_name = 'kas_warenhuis'
thres_alpha = 0.25
thres_reg_line_dist = 0.59999999999999998
thres_reg_line_ext = 3.0